kind: PersistentVolume
apiVersion: v1
metadata:
  name: auth-volume
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/syed/work/kubernetes/docker-registry/auth"
  claimRef:
    kind: PersistentVolumeClaim
    namespace: default
    name: auth-volume