apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 1-auth-pv.yml
  - 2-certs-pv.yaml
  - 3-img-vol-pv.yaml
  - docker-registry-claim0-persistentvolumeclaim.yaml
  - docker-registry-claim1-persistentvolumeclaim.yaml
  - docker-registry-claim2-persistentvolumeclaim.yaml
  - docker-registry-deployment.yaml
  - docker-registry-service.yaml
